envs:
- key: DISABLE_COLLECTSTATIC
  scope: RUN_AND_BUILD_TIME
  value: "1"
name: bacs350-app
region: nyc
services:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: eduffield/PythonWebApps
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: bacs350-app-demo
  routes:
  - path: /
  run_command: |
    python manage.py migrate --no-input
    gunicorn --worker-tmp-dir /dev/shm config.wsgi
  source_dir: Student/04/Gallery
static_sites:
- environment_slug: html
  github:
    branch: main
    deploy_on_push: true
    repo: eduffield/PythonWebApps
  name: bacs350-app-static
  routes:
  - path: /static
  source_dir: Student/04/Gallery/static
