# Generated by Django 4.2.4 on 2023-09-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Superhero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heroid', models.TextField()),
                ('name', models.CharField(max_length=200)),
                ('strengths', models.TextField()),
                ('weaknesses', models.TextField()),
            ],
        ),
    ]
